import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        <nav className="p-4 bg-gray-800 text-white">
  <ul className="flex gap-4">
    <li>
      <a href="/dashboard" className="hover:underline">
        Dashboard
      </a>
    </li>
    <li>
      <a href="/test-upload" className="hover:underline">
        Add Item
      </a>
    </li>
    <li>
      <a href="/upload-outfit" className="hover:underline">
        Add Outfit
      </a>
    </li>
    <li>
      <a href="/past-outfits" className="hover:underline">
        Past Outfit
      </a>
    </li>
    <li>
      <a href="/weather" className="hover:underline">
        Weather & Outfit
      </a>
    </li>
  </ul>
</nav>
{children}</body>
      </html>
    </ClerkProvider>
  );
}
